### ISSUE TITLE
Android Studio: Preview rendering problems for layout file

### ISSUE THREAD

**Issue by johnjohndoe** [dlukashev/AndroidSlidingUpPanel-foursquare-map-demo#4]
When I want to see the visual layout for `activity_main.xml` in Android Studio 0.8.12 the following rendering error occurs:

```
java.lang.NullPointerException
    at com.sothree.slidinguppanel.SlidingUpPanelLayout.computeScroll(SlidingUpPanelLayout.java:1000)
    at android.view.View.draw(View.java:14587)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3234)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3037)
    at android.view.View.draw(View.java:14739)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3234)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3037)
    at android.view.View.draw(View.java:14739)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3234)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3037)
    at android.view.View.draw(View.java:14842)
    at com.android.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:501)
    at android.view.View.draw(View.java:14741)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3234)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3037)
    at android.view.View.draw(View.java:14739)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3234)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3037)
    at android.view.View.draw(View.java:14842)
    at android.view.View.draw(View.java:14741)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3234)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3037)
    at android.view.View.draw(View.java:14842)
    at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:587)
    at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:331)
    at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:333)
    at com.android.tools.idea.rendering.RenderService$5.compute(RenderService.java:674)
    at com.android.tools.idea.rendering.RenderService$5.compute(RenderService.java:663)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
    at com.android.tools.idea.rendering.RenderService.createRenderSession(RenderService.java:663)
    at com.android.tools.idea.rendering.RenderService.render(RenderService.java:790)
    at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:611)
    at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1900(AndroidLayoutPreviewToolWindowManager.java:81)
    at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:553)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
    at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:548)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
    at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:327)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

Do you have a clue why this is happening?

**Comment by dlukashev** [comment]
fixed in https://github.com/dlukashev/AndroidSlidingUpPanel-foursquare-map-demo/commit/398946afedfc8d959af5eac72521a0d82e748f09

**Comment by johnjohndoe** [comment]
:+1:
